---
swagger: "2.0"
info:
  description: Simple API
  version: 1.0.0
  title: HomeWork8
host: localhost:8080
basePath: /api
tags:
- name: products
  description: Products methods
- name: users
  description: Users methods
- name: cities
  description: Cities methods
schemes:
- http
paths:
  /products:
    get:
      tags:
      - products
      summary: Return all products
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: fetched products
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
          responseSchema:
            type: array
            items:
              $ref: '#/definitions/Product'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/inline_response_500'
          responseSchema:
            type: object
            properties:
              error:
                type: string
                example: Client is not connected to the database.
    post:
      tags:
      - products
      summary: Add product
      produces:
      - application/json
      parameters:
      - in: body
        name: product
        description: Add product item
        required: false
        schema:
          properties:
              name:
                type: string
                example: Nuts.
      responses:
        200:
          description: return added product item
          schema:
            $ref: '#/definitions/Product'
          responseSchema:
            $ref: '#/definitions/Product'
        400:
          description: Validation error
          schema:
            $ref: '#/definitions/inline_response_400'
          responseSchema:
            type: object
            properties:
              error:
                type: string
                example: Validation error.
        500:
          description: database error
          schema:
            $ref: '#/definitions/inline_response_500'
          responseSchema:
            type: object
            properties:
              error:
                type: string
                example: Client is not connected to the database.
  /products/{id}:
    get:
      tags:
      - products
      summary: Return project by id
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        description: Product's identifier
        required: true
        type: string
      responses:
        200:
          description: return found item
          schema:
            $ref: '#/definitions/Product'
          responseSchema:
            $ref: '#/definitions/Product'
        404:
          description: item wasn't found
          schema:
            $ref: '#/definitions/inline_response_404'
        500:
          description: database error
          schema:
            $ref: '#/definitions/inline_response_500'
          responseSchema:
            type: object
            properties:
              error:
                type: string
                example: Client is not connected to the database.
    delete:
      tags:
      - products
      summary: Delete product by id
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        description: Product's identifier
        required: true
        type: string
      responses:
        200:
          description: delete product by id
          schema:
            type: string
            example: OK.
          responseSchema:
            type: string
            example: OK.
        404:
          description: product wasn't found
          schema:
            $ref: '#/definitions/inline_response_404'
        500:
          description: database error
          schema:
            $ref: '#/definitions/inline_response_500'
          responseSchema:
            type: object
            properties:
              error:
                type: string
                example: Client is not connected to the database.
  /users:
    get:
      tags:
      - users
      summary: Return all users
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: fetched users
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
          responseSchema:
            type: array
            items:
              $ref: '#/definitions/User'
        500:
          description: database error
          schema:
            $ref: '#/definitions/inline_response_500'
          responseSchema:
            type: object
            properties:
              error:
                type: string
                example: Client is not connected to the database.
  /users/{id}:
    delete:
      tags:
      - users
      summary: Delete user by id
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        description: User's identifier
        required: true
        type: string
      responses:
        200:
          description: delete product by id
          schema:
            type: string
            example: OK.
          responseSchema:
            type: string
            example: OK.
        404:
          description: user wasn't found
          schema:
            $ref: '#/definitions/inline_response_404'
        500:
          description: database error
          schema:
            $ref: '#/definitions/inline_response_500'
          responseSchema:
            type: object
            properties:
              error:
                type: string
                example: Client is not connected to the database.
  /cities:
    get:
      tags:
      - cities
      summary: Return all cities
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: fetched cities
          schema:
            type: array
            items:
              $ref: '#/definitions/City'
          responseSchema:
            type: array
            items:
              $ref: '#/definitions/City'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/inline_response_500'
          responseSchema:
            type: object
            properties:
              error:
                type: string
                example: Client is not connected to the database.
    post:
      tags:
      - cities
      summary: Add city
      produces:
      - application/json
      parameters:
      - in: body
        name: Brest
        country: Belarus
        capital: false
        location:
          lat: 52.097621
          long: 23.73405
        description: Add city item
        required: false
        schema:
          properties:
            name:
              type: string
              example: Brest
            country:
              type: string
              example: Belarus
            capital:
              type: boolean
              example: false
            location:
              type: object
              properties:
                lat:
                  type: number
                  example: 52.097621
                long:
                  type: number
                  example: 23.73405
              
      responses:
        200:
          description: return added product item
          schema:
            $ref: '#/definitions/City'
          responseSchema:
            $ref: '#/definitions/City'
        400:
          description: Validation error
          schema:
            $ref: '#/definitions/inline_response_400'
          responseSchema:
            type: object
            properties:
              error:
                type: string
                example: Validation error.
        500:
          description: database error
          schema:
            $ref: '#/definitions/inline_response_500'
          responseSchema:
            type: object
            properties:
              error:
                type: string
                example: Client is not connected to the database.
  /cities/{id}:
    delete:
      tags:
      - cities
      summary: Delete city by id
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        description: City's identifier
        required: true
        type: string
      responses:
        200:
          description: delete city by id
          schema:
            type: string
            example: OK.
          responseSchema:
            type: string
            example: OK.
        404:
          description: city wasn't found
          schema:
            $ref: '#/definitions/inline_response_404'
        500:
          description: database error
          schema:
            $ref: '#/definitions/inline_response_500'
          responseSchema:
            type: object
            properties:
              error:
                type: string
                example: Client is not connected to the database.
  /cities/random:
    get:
      tags:
      - cities
      summary: Return random city
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: random city
          schema:
            type: array
            items:
              $ref: '#/definitions/City'
          responseSchema:
            type: array
            items:
              $ref: '#/definitions/City'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/inline_response_500'
          responseSchema:
            type: object
            properties:
              error:
                type: string
                example: Client is not connected to the database.
definitions:
  Product:
    type: object
    required:
    - name
    properties:
      _id:
        type: string
        format: uuid
        example: 5b4de63ca37ef415b7d0206f
      name:
        type: string
        example: Beer
    example:
      name: Beer
      _id: 5b4de63ca37ef415b7d0206f
  User:
    type: object
    properties:
      _id:
        type: string
        format: uuid
        example: 5b4de63ca37ef415b7d0206f
      firstName:
        type: string
        example: user's firstName
      surName:
        type: string
        example: user's surName
    example:
      firstName: user's firstName
      surName: user's surName
      _id: 5b4de63ca37ef415b7d0206f
  City:
    type: object
    required:
    - name
    properties:
      name:
        type: string
      country:
        type: string
      capital:
        type: boolean
      _id:
        type: string
        format: uuid
      location:
        type: object
        properties:
          lat: number
          long: number
    example:
      name: Brest
      country: Belarus
      capital: false
      location:
        lat: 52.097621
        long: 23.73405
      _id: 5b4de63ca37ef415b7d0206f
  inline_response_500:
    properties:
      error:
        type: string
        example: The server encountered an unexpected condition which prevented it from fulfilling the request.
  inline_response_404:
    properties:
      error:
        type: string
        example: The server has not found anything matching the URI given.
  inline_response_400:
    properties:
      error:
        type: string
        example: Validation error.
responses:
  DBError:
    description: database error
    schema:
      type: object
      properties:
        error:
          type: string
          example: Client is not connected to the database.
    responseSchema:
      type: object
      properties:
        error:
          type: string
          example: Client is not connected to the database.
